name: Infection

on: [ pull_request ]

jobs:
  build:

    if: "!contains(github.event.pull_request.labels.*.name, 'skip-infection')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]
        prefer-lowest: [ '--prefer-lowest', '' ]

    name: Infection on PHP ${{ matrix.php }} ${{ matrix.prefer-lowest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov
          ini-values: zend.assertions=1

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-progress ${{ matrix.prefer-lowest }}

      - name: Infection
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection \
              -j$(nproc) \
              --git-diff-lines \
              --git-diff-base=origin/$GITHUB_BASE_REF \
              --min-msi=100 \
              --min-covered-msi=100 \
              --ignore-msi-with-no-mutations
