name: PHPCS

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]
        prefer-lowest: [ '--prefer-lowest', '' ]

    name: PHPCS on PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-progress ${{ matrix.prefer-lowest }}

      - name: Check code style
        run: vendor/bin/phpcs --parallel=$(nproc)
